run:
  skip-dirs:
    - doc
    - testdata
  tests: false

linters:
  disable:
    - lll
    - maligned
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goconst
    - bodyclose
  presets:
      - bugs
      - complexity
      - format
      - performance
      - style
      - unused

linters-settings:
  funlen:
    lines: 70
